### ISSUE TITLE
Any news about oauth user client authentication?

### ISSUE THREAD

**Issue by ghost** [octokit/auth.js#172]
In the README there is a strategy called "oauth user client authentication" (https://github.com/octokit/authentication-strategies.js/?tab=readme-ov-file#oauth-user-client-authentication) that allows to authenticate non-secure clients that does not have a clientSecret. There is no work done in the reported repository in the last 3 years.. Is it a wanted feature? I need this for a CLI, is there any other viable option?

**Comment by gr2m** [comment]
> I need this for a CLI, is there any other viable option

For a CLI, you usually want to use the device authentication flow:
https://github.com/octokit/auth-oauth-device.js#readme

**Comment by ghost** [comment]
THank you @gr2m , I didn't know that.. I'll take a look to that flow!
Maybe it's the case to update the docs about the user client authentication if it's a stalled project?

**Comment by gr2m** [comment]
I wouldn't say it's stalled, it's open source, anyone can pick it up when they need it, and we already linked to the current state of it. I think we are good.
